# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md

required = [
  "github.com/goadesign/goa/cors",
  "github.com/goadesign/goa/encoding/form",
  "github.com/goadesign/goa/goagen",
  "github.com/goadesign/goa/goagen/codegen",
  "github.com/goadesign/goa/goagen/gen_app",
  "github.com/goadesign/goa/goagen/gen_controller",
  "github.com/goadesign/goa/goagen/gen_swagger",
  "github.com/goadesign/goa/goagen/gen_client",
  "github.com/goadesign/goa/goagen/gen_js",
  "github.com/goadesign/goa/goagen/utils",
  "github.com/goadesign/goa/goatest",
]

[[constraint]]
  name = "github.com/goadesign/goa"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
